# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Investigando Dados Abertos do Governo Brasileiro
email: "&#099;&#101;&#109;&#115;&#064;&#099;&#101;&#109;&#115;&#104;&#111;&#115;&#116;&#046;&#099;&#111;&#109;&#046;&#098;&#114;"
description: > # this means to ignore newlines until "baseurl:"
  Análises reprodutíveis de dados do governo brasileiro. Aprenda mais sobre
  política, Python e aprendizagem de máquina (machine learning).
baseurl: "/dados.gov.br" # the subpath of your site, e.g. /blog
url: "https://cemsbr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cemsbr
github_username:  cemsbr

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
    shortname: cemsbr-dados-gov-br

google_analytics: UA-86123067-1
